name: Consumer Contract Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read # Access to download the stubs
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Run Consumer Tests
          # We pass the serverId and force the credentials via system properties
        run: >
          mvn test 
          -s ${{ github.workspace }}/settings.xml 
          -Dstubrunner.serverId=github 
          -Dstubrunner.username=gayatripande
          -Dstubrunner.password=${{ secrets.STUB_TOKEN }}
        env:
          # We provide it as an env var just in case settings.xml looks for it
          GITHUB_TOKEN: ${{ secrets.STUB_TOKEN }}
